spring: 
    application: 
        name: finalProjectChat

    datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    jwt:
        refresh:
            cookie:
                name: refresh
            expired: 86400000
        access:
            expired: 36400000
        secret: 
            code: zX9#mK2$pL7@qR5^vN3&hB6*fD1!jW8%cT4(uY0)sA2_eG5+iO9=lQ7
logging:
    level:
        org:
        springframework:
            web:
            socket: DEBUG
            messaging: DEBUG
            bean:
            factory:
                support: DEBUG
        security: DEBUG

app:
    frontend-url: http://localhost:4173
    frontend-admin-url: http://localhost:7001
    domain: localhost
    dev-mode: true